/*
 * IPX_BipolarDriver.c
 *
 * Created: 29-May-17 10:41:49 AM
 *  Author: ScorpionIPX
 */ 

#include "Global.h"
#include "IPX_BipolarDriver.h"
#include <util/delay.h>


void init_bipolar_control(void)
{
	MOTOR_DDR |= (1 << MOTOR_COIL_A_POSITIVE) | (1 << MOTOR_COIL_A_NEGATIVE) | (1 << MOTOR_COIL_B_POSITIVE) | (1 << MOTOR_COIL_B_NEGATIVE);
	MOTOR_PORT &= ~((1 << MOTOR_COIL_A_POSITIVE) | (1 << MOTOR_COIL_A_NEGATIVE) | (1 << MOTOR_COIL_B_POSITIVE) | (1 << MOTOR_COIL_B_NEGATIVE));
}


void bipolar_drive_forward()
{
	unsigned int STEP_DELAY_MS = 20;
	unsigned int TURN_OFF_DELAY_Ms = 10;
	
	MOTOR_STEP_1;
	_delay_ms(TURN_OFF_DELAY_Ms);
	MOTOR_OFF;
	_delay_ms(STEP_DELAY_MS - TURN_OFF_DELAY_Ms);
	
	MOTOR_STEP_2;
	_delay_ms(TURN_OFF_DELAY_Ms);
	MOTOR_OFF;
	_delay_ms(STEP_DELAY_MS - TURN_OFF_DELAY_Ms);
	
	MOTOR_STEP_3;
	_delay_ms(TURN_OFF_DELAY_Ms);
	MOTOR_OFF;
	_delay_ms(STEP_DELAY_MS - TURN_OFF_DELAY_Ms);
	
	MOTOR_STEP_4;
	_delay_ms(TURN_OFF_DELAY_Ms);
	MOTOR_OFF;
	_delay_ms(STEP_DELAY_MS - TURN_OFF_DELAY_Ms);
}

void bipolar_drive_forward_full_torque()
{
	unsigned int STEP_DELAY_MS = 2;
	
	MOTOR_STEP_1;
	_delay_ms(STEP_DELAY_MS);
	
	MOTOR_STEP_2;
	_delay_ms(STEP_DELAY_MS);
	
	MOTOR_STEP_3;
	_delay_ms(STEP_DELAY_MS);
	
	MOTOR_STEP_4;
	_delay_ms(STEP_DELAY_MS);
}

void bipolar_drive_forward_full_step()
{
	unsigned int STEP_DELAY_MS = 100;
	
	SET_COIL_A_POSITIVE;
	RESET_COIL_A_NEGATIVE;
	RESET_COIL_B_POSITIVE;
	SET_COIL_B_NEGATIVE;
	_delay_ms(STEP_DELAY_MS/2);
	
	SET_COIL_A_POSITIVE;
	SET_COIL_A_NEGATIVE;
	RESET_COIL_B_POSITIVE;
	RESET_COIL_B_NEGATIVE;
	_delay_ms(STEP_DELAY_MS/2);
	
	RESET_COIL_A_POSITIVE;
	SET_COIL_A_NEGATIVE;
	SET_COIL_B_POSITIVE;
	RESET_COIL_B_NEGATIVE;
	_delay_ms(STEP_DELAY_MS/2);

	RESET_COIL_A_POSITIVE;
	RESET_COIL_A_NEGATIVE;
	SET_COIL_B_POSITIVE;
	SET_COIL_B_NEGATIVE;
	_delay_ms(STEP_DELAY_MS/2);
	
}

void bipolar_drive_forward_half_step()
{
	unsigned int STEP_DELAY_MS = 10;
	
	RESET_COIL_A_POSITIVE;
	RESET_COIL_A_NEGATIVE;
	RESET_COIL_B_POSITIVE;
	SET_COIL_B_NEGATIVE;
	_delay_ms(STEP_DELAY_MS);
	
	SET_COIL_A_POSITIVE;
	RESET_COIL_A_NEGATIVE;
	RESET_COIL_B_POSITIVE;
	SET_COIL_B_NEGATIVE;
	_delay_ms(STEP_DELAY_MS);
	
	SET_COIL_A_POSITIVE;
	RESET_COIL_A_NEGATIVE;
	RESET_COIL_B_POSITIVE;
	RESET_COIL_B_NEGATIVE;
	_delay_ms(STEP_DELAY_MS);

	SET_COIL_A_POSITIVE;
	SET_COIL_A_NEGATIVE;
	RESET_COIL_B_POSITIVE;
	RESET_COIL_B_NEGATIVE;
	_delay_ms(STEP_DELAY_MS);
	
	RESET_COIL_A_POSITIVE;
	SET_COIL_A_NEGATIVE;
	RESET_COIL_B_POSITIVE;
	RESET_COIL_B_NEGATIVE;
	_delay_ms(STEP_DELAY_MS);
	
	RESET_COIL_A_POSITIVE;
	SET_COIL_A_NEGATIVE;
	SET_COIL_B_POSITIVE;
	RESET_COIL_B_NEGATIVE;
	_delay_ms(STEP_DELAY_MS);
	
	RESET_COIL_A_POSITIVE;
	RESET_COIL_A_NEGATIVE;
	SET_COIL_B_POSITIVE;
	RESET_COIL_B_NEGATIVE;
	_delay_ms(STEP_DELAY_MS);

	RESET_COIL_A_POSITIVE;
	RESET_COIL_A_NEGATIVE;
	SET_COIL_B_POSITIVE;
	SET_COIL_B_NEGATIVE;
	_delay_ms(STEP_DELAY_MS);
	
}

